### ISSUE TITLE
No models provided to run sample case

### ISSUE THREAD

**Issue by jsborca** [Ryuto10/pzero-improves-zar#4]
In the documentation for the [demo](https://github.com/Ryuto10/pzero-improves-zar/blob/main/docs/demo.md),  you make reference to the below models:
```
Base Model: data/cloze.as.seed5000.model
Proposed Model: data/pzero.as-pzero.seed5000.model
```

And tell the reader to run the model qith
```
$ INPUT_TEXT=/path/to/parsed_text
$ MODEL=/path/to/model
$ poetry run python src/run.py --parsed_text $INPUT_TEXT --model $MODEL --model_type "as-pzero"
```

But nowhere in the repo could I find Base or Proposed model.

Is the reader expected to train the as and as-pzero models themselves? This seems unlikely as there does not seem to be any training data either.

If so, how is the reader expected to provide either model for the demo script?

**Comment by Ryuto10** [comment]
You can download the model parameters from [Github releases](https://github.com/Ryuto10/pzero-improves-zar/releases/tag/ver.1.0) and run the demo.
- `cloze.as.seed5550.model`
- `pzero.as-pzero.seed5550.model`

Thank you for your suggestion.
I will revise the documentation to be more clear.

![image](https://user-images.githubusercontent.com/36494348/222719362-c132aa4c-e17d-4cfa-a5fd-bf1599a35e49.png)

**Comment by jsborca** [comment]
Thank you - highly appreaciated!
